name: cellitaire-rl
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - ipykernel
  - jupyter
  - matplotlib
  - pytorch
  - gymnasium
  - pygame
  # FOR CUDA ADD CUDA-TOOLKIT DEPENDENCY

