import pygame

GU_SLOT_UPDATE = pygame.USEREVENT + 1
GU_FOUNDATION_UPDATE = pygame.USEREVENT + 2
GU_STOCKPILE_UPDATE = pygame.USEREVENT + 3

SLOT_CLICKED = pygame.USEREVENT + 4

REWARD_UPDATED = pygame.USEREVENT + 5
RESET = pygame.USEREVENT + 6