SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_DIMS = (SCREEN_WIDTH, SCREEN_HEIGHT)

RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
PURPLE = (112, 1, 169)
YELLOW = (255, 255, 0)
BLACK = (0, 0, 0)

SCREEN_MARGIN = 15

BOARD_MARGIN = 15
SLOT_WIDTH = 120
SLOT_HEIGHT = 120
SLOT_PADDING = 5
SLOT_BACKGROUND_COLOR = GREEN
SLOT_LONELY_OR_SUFFOCATED_COLOR = PURPLE
SLOT_PLACEABLE_COLOR = YELLOW

STOCKPILE_WIDTH = SLOT_WIDTH * 2
STOCKPILE_HEIGHT = SLOT_HEIGHT
STOCKPILE_PADDING = 5
STOCKPILE_BACKGROUND_COLOR = BLACK

FOUNDATION_WIDTH = SLOT_WIDTH * 5
FOUNDATION_HEIGHT = STOCKPILE_HEIGHT
FOUNDATION_PADDING = 5
FOUNDATION_PILE_OUTLINE_COLOR = YELLOW
FOUNDATION_BACKGROUND_COLOR = BLACK

BACKGROUND_COLOR = BLUE


def get_card_text_color(card):
    return {
        's': BLACK,
        'h': RED,
        'd': BLUE,
        'c': GREEN
    }[card.suit]
